# frozen_string_literal: true

source "https://rubygems.org"

gemspec

DECIDIM_VERSION = { git: "https://github.com/CodiTramuntana/decidim.git", branch: "release/0.27-stable" }.freeze

group :development, :test do
  gem "bootsnap"
  gem "decidim", DECIDIM_VERSION
  gem "letter_opener_web"
  gem "listen"
  gem "pry-rails"

  # temporal solution while gems embrace new psych 4 (the default in Ruby 3.1) behavior.
  gem "psych", "< 4"
end
